### ISSUE TITLE
Ask for help: Backend quit unexpectedly

### ISSUE THREAD

**Issue by rickyyin98** [divamgupta/diffusionbee-stable-diffusion-ui#29]
<img width="850" alt="截屏2022-09-13 12 48 26" src="https://user-images.githubusercontent.com/24710596/189811308-6d950372-2ea8-43c8-9992-db38cef8b257.png">

More info:
Version: Ventura 13.0 (22A5295i)

**Comment by ee0pdt** [comment]
Happened to me, just quit and restarted and all was fine

**Comment by rickyyin98** [comment]
> Happened to me, just quit and restarted and all was fine

I quit and restart for many times, but still not work.
So I try to find a way.

**Comment by ctparton** [comment]
I'm having the same issue on MacOS 12.6

**Comment by schoeM** [comment]
I'm seeing the same on 12.6
`Uncaught Exception:
TypeError: Object has been destroyed
at IpcMainImpl.<anonymous> (/Applications/DiffusionBee.app/Contents/Resources/app.asar/background.js:2:240352)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:161:10307)
at Object.emit (events.js:315:20)
at ChildProcess.<anonymous> (/Applications/DiffusionBee.app/Contents/Resources/app.asar/background.js:2:244979)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1048:16)
at Socket.<anonymous> (internal/child_process.js:439:11)
at Socket.emit (events.js:315:20)
at Pipe.<anonymous> (net.js:673:12)`

**Comment by mindfu23** [comment]
Also seeing the same issue and same error. Mac Mini M1. Fresh install of 12.6, restarted and reinstalled DiffusionBee several times. Same message. 
I wonder if this is due to 12.6 and not 12.5?

**Comment by greatoe** [comment]
Same issue here.

MacBook Pro 16inch 2021
Apple M1 Max
64Gb RAM, most other apps closed
macOS 12.6

**Comment by greatoe** [comment]
Same issue here.

MacBook Pro 16inch 2021
Apple M1 Max
64Gb RAM, most other apps closed
macOS 12.6

**Comment by holygrolli** [comment]
Had the exact same error. I realized my internet connection filter (TripMode) blocked traffic of this unknown app. After enabling internet access for DiffusionBee it started downloading the model.

**Comment by Sowiedu** [comment]
I can confirm the blocked internet access is the solution.

**Comment by mattq2022** [comment]
How did you "unblock" the app? I have allowed in the firewall and even tried turning the firewall off; neither worked

**Comment by allanjackson** [comment]
Download the 1.4.3 version, that should fix this issue.

**Comment by mattq2022** [comment]
Yeah, I have a intel Mac, so the newer versions do not work

**Comment by anshuzy** [comment]
Hey! I just installed the latest version of Diffusion Bee 1.5.1 and this is the exact error that's happening to me. The models just refuse to download. I tried all of the steps that you guys said and it still isn't working. Anyone have an updated solution?
Specs: M1 Pro, 16gb ram, MacOS 13.0.1

**Comment by anshuzy** [comment]
I keep getting this error

Backend quit unexpectedly.  call last):
File "diffusionbee_backend.py", line 256, in <module>
File "diffusionbee_backend.py", line 216, in main
File "diffusionbee_backend.py", line 113, in get_sd_model
NameError: name 'p2' is not defined
[1059] Failed to execute script 'diffusionbee_backend' due to unhandled exception!
